export const THAI_PROVINCES = [
  'Bangkok',
  // 'Samut Prakan',
  // 'Nonthaburi',
  // 'Pathum Thani',
  // 'Phra Nakhon Si Ayutthaya',
  // 'Ang Thong',
  // 'Lopburi',
  // 'Sing Buri',
  // 'Chai Nat',
  // 'Saraburi',
  // 'Chonburi',
  // 'Rayong',
  // 'Chanthaburi',
  // 'Trat',
  // 'Chachoengsao',
  // 'Prachinburi',
  // 'Nakhon Nayok',
  // 'Sa Kaeo',
  // 'Nakhon Ratchasima',
  // 'Buri Ram',
  // 'Surin',
  // 'Si Sa Ket',
  // 'Ubon Ratchathani',
  // 'Yasothon',
  // 'Chaiyaphum',
  // 'Amnat Charoen',
  // 'Bueng Kan',
  // 'Nong Bua Lamphu',
  // 'Khon Kaen',
  // 'Udon Thani',
  // 'Loei',
  // 'Nong Khai',
  // 'Maha Sarakham',
  // 'Roi Et',
  // 'Kalasin',
  // 'Sakon Nakhon',
  // 'Nakhon Phanom',
  // 'Mukdahan',
  // 'Chiang Mai',
  // 'Lamphun',
  // 'Lampang',
  // 'Uttaradit',
  // 'Phrae',
  // 'Nan',
  // 'Phayao',
  // 'Chiang Rai',
  // 'Mae Hong Son',
  // 'Nakhon Sawan',
  // 'Uthai Thani',
  // 'Kamphaeng Phet',
  // 'Tak',
  // 'Sukhothai',
  // 'Phitsanulok',
  // 'Phichit',
  // 'Phetchabun',
  // 'Ratchaburi',
  // 'Kanchanaburi',
  // 'Suphan Buri',
  // 'Nakhon Pathom',
  // 'Samut Sakhon',
  // 'Samut Songkhram',
  // 'Phetchaburi',
  // 'Prachuap Khiri Khan',
  // 'Nakhon Si Thammarat',
  // 'Krabi',
  // 'Phang Nga',
  // 'Phuket',
  // 'Surat Thani',
  // 'Ranong',
  // 'Chumphon',
  // 'Songkhla',
  // 'Satun',
  // 'Trang',
  // 'Phatthalung',
  // 'Pattani',
  // 'Yala',
  // 'Narathiwat',
];
