name: build-project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        if: false # Workflow temporarily disabled
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 24

            - name: Build frontend
              working-directory: ./frontend
              run: |
                  npm ci
                  npm run build:web

            - name: Build backend
              working-directory: ./backend
              run: |
                  npm ci
                  npm run build
